name: DB check

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
    paths:
      - 'db/**'
      - 'text/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  workflow_dispatch:

jobs:
  db-check:
    uses: Warhammer-Mods/workflows/.github/workflows/db-check.yml@v1
    with:
      paths: db text
      vscode_workspace_file: .vscode/arkhan_stevie.code-workspace
      pr_enabled: true
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
