name: DB check

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
    paths:
      - 'db/**'
      - 'text/**'
      - '.github/workflows/**'
      - '.vscode/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  workflow_dispatch:

env:
  FILES_TO_CHECK: >- # list of files and folders, relative to the repo root path
    db
    text
  GIT_AUTHOR_NAME: "github-actions[bot]"
  GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GIT_COMMITTER_NAME: "github-actions[bot]"
  GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  CSVLINT_PATH: "csvlint" #relative to $HOME

jobs:

  db-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Cache dos2unix
      id: cache-dos2unix
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dos2unix-cache
        path: "~/dos2unix"

    - name: Install dos2unix
      env:
        CACHE_HIT: ${{steps.cache-dos2unix.outputs.cache-hit}}
      run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/dos2unix/* /
          else
            sudo apt-get install --yes dos2unix
            mkdir -p ~/dos2unix
            sudo dpkg -L dos2unix | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/dos2unix/
          fi

    - name: Normalize LF/CRLF
      run: |
        for path in ${FILES_TO_CHECK}; do
          if [[ -d ${path} ]]; then
            find ${path} -type f -iname "*.tsv" -exec dos2unix {} \;
          elif [[ -f ${path} ]]; then
            dos2unix ${path}
          fi
        done 

    - name: Set csvlint info
      id: csvlint-info
      run: |
        api="api.github.com"
        repo="Clever/csvlint"

        response=$(
          curl -sL "https://${api}/repos/${repo}/releases/latest" |
          jq -rc
        )

        version="$(jq -r '.name' <<< ${response})"
        download_url="$(jq -r '.assets[].browser_download_url' <<< ${response} | grep -i "$(uname -s)")"

        echo "::set-output name=json::${response}"
        echo "::set-output name=latest-version::${version}"
        echo "::set-output name=download-url::${download_url}"

        if [[ -z ${{ env.CSVLINT_PATH }} ]]; then
          echo "CSVLINT_PATH=${HOME}/csvlint" >> ${GITHUB_ENV}
        fi

    - name: Cache cvslint
      id: csvlint-cache
      uses: actions/cache@v2
      with:
        key: "${{ runner.os }}-csvlint@${{ steps.csvlint-info.outputs.latest-version }}"
        path: "~/${{ env.CSVLINT_PATH }}"

    - if: steps.csvlint-cache.outputs.cache-hit == 'true'
      run: echo "${HOME}/${{ env.CSVLINT_PATH }}" >> ${GITHUB_PATH}

    - name: Install csvlint
      id: csvlint-install
      if: steps.csvlint-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${HOME}/${{ env.CSVLINT_PATH }}
        curl -sL ${{ steps.csvlint-info.outputs.download-url }} |
          tar -xzvf - --strip-components=1 -C ${HOME}/${{ env.CSVLINT_PATH }}
        echo "${HOME}/${{ env.CSVLINT_PATH }}" >> ${GITHUB_PATH}
    
    - name: Check TSV syntax
      id: check_syntax
      shell: bash --noprofile --norc {0}
      run: |
        exit_code=0
        checkTSV () {
          echo "File: ${file}"
          csvlint --delimiter='\t' "${file}"
          exitstatus=$?
          echo "::debug::Check finished with exit code: ${exitstatus}"
          return $exitstatus
        }

        exit_code=0
        echo "::add-matcher::.github/csvlint.json"
        for path in ${{ env.FILES_TO_CHECK }}; do
          
          if [[ -d ${path} ]]; then
            for file in $(find ${path} -type f -iname "*.tsv"); do
              checkTSV "$file"
              exitstatus=$?
            done
          elif [[ -f ${path} ]]; then
            checkTSV "${path}"
            exitstatus=$?
          fi
          
          (( $exit_code < $exitstatus )) && exit_code=$exitstatus
        done
        echo "::remove-matcher owner=csvlint_error::"
        echo "::remove-matcher owner=csvlint_warning::"
        
        echo "::debug::Exiting with code: ${exit_code}"
        exit ${exit_code}

    - name: Get file changes
      id: changes
      run: |
        changes="$(git status --porcelain=1 ${FILES_TO_CHECK})"
        echo "::debug::${changes}"
        if [ -z "${changes}" ]; then
          echo "::set-output name=clean::true"
        else
          files=()
          while IFS= read -r line; do
            file=$(cut -d" " -f3 <<< ${line})
            files+=("${file}")
            echo "::notice file=${file}::File changed: ${line}"
            echo "::debug::$(git diff ${file})"
          done <<< ${changes}
          echo "::set-output name=files::${files[@]}"
          echo "::set-output name=clean::false"
        fi

    - name: Upload DBs
      if: steps.changes.outputs.clean == 'false'
      uses: actions/upload-artifact@v2
      with:
        name: fixed-dbs
        path: ${{ steps.changes.outputs.files }}

  create-pr:
    runs-on: ubuntu-latest
    needs: db-check
    if: needs.db-check.outputs.clean == 'false'

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Download DBs
      uses: actions/download-artifact@v2
      with:
        name: fixed-dbs

    - name: Commit files
      id: commit
      run: |
        git config --local user.email ${{ env.GIT_AUTHOR_EMAIL }}
        git config --local user.name ${{ env.GIT_AUTHOR_NAME }}
        git add ${FILES_TO_CHECK}
        git commit -m "[DB Check] Fix DBs"
        if ${{ startsWith(github.ref, 'refs/tags/') }}; then
          git tag -fa ${{ github.ref }}
        fi

    - name: Create a PR
      id: pr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.BOT_TOKEN }}
        committer: ${{ format( '{0} <{1}>', env.GIT_COMMITTER_NAME, env.GIT_COMMITTER_EMAIL) }}
        author: ${{ format( '{0} <{1}>', env.GIT_AUTHOR_NAME, env.GIT_AUTHOR_EMAIL) }}
        branch: bot/tsv-patch
        branch-suffix: short-commit-hash
        delete-branch: true
        signoff: false
        title: "[DB Check] Fix DBs"
        body: |
          **Fixes**:
            - Line ending normalization
        labels: |
          automation

    - name: Show info
      run: |
        echo "::notice::${{ format(
          'Pull request #{0} is {1}: {2}',
          steps.pr.outputs.pull-request-number,
          steps.pr.outputs.pull-request-operation,
          steps.pr.outputs.pull-request-url
        ) }}"

    - name: Enable Pull Request Automerge
      if: steps.pr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v1
      with:
        token: ${{ secrets.BOT_TOKEN }}
        pull-request-number: ${{ steps.pr.outputs.pull-request-number }}
        merge-method: squash
