name: lint

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"

    - name: lint
      run: |
        luac script/_lib/mod/*.lua \
             script/campaign/mod/*.lua
