name: Lua lint

on: 
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'
  workflow_dispatch:

env:
  FILES_TO_CHECK: >-
    script/{_lib/,campaign}
  VENDOR_PATH: script/.vscode
  CUSTOM_LUA_GLOBALS: >-
    ardm

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"
        
    - uses: leafo/gh-actions-luarocks@v4.1.0
      with:
        luarocksVersion: "3.7.0"
        
    - name: Install luacheck
      run: luarocks install luacheck

    - name: Install show_globals.lua (courtesy of Egor Skriptunoff)
      run: |
        wget -O show_globals.lua \
          https://gistcdn.githack.com/Egor-Skriptunoff/e4ab3bfc777faf4482a1b3f3ae19181b/raw/a39198cf62a52be7956abbff145a7fbf3f9a128a/show_globals.lua

    - name: Get Lua globals from vendor path
      id: lua-globals
      run: |
        lua_files=$(find ${{ env.VENDOR_PATH }} -type f -iname "*.lua")
        globals=$(
          for f in $lua_files; do
            lua show_globals.lua W < $f | cut -f2
          done
          printf '%s' ${{ env.CUSTOM_LUA_GLOBALS }}
        )
        globals=$(tr ' ' '\n' <<<"${globals}" | sort -u | tr '\n' ' ')
        echo "::set-output name=globals::$globals"

    - name: Luacheck Lint
      id: luacheck
      shell: bash --noprofile --norc {0}
      run: |
        mkdir output
        echo "::add-matcher::.github/luacheck-plain.json"
        luacheck ${{ env.FILES_TO_CHECK }} \
          --formatter plain \
          --codes --ranges \
          --globals ${{ steps.lua-globals.outputs.globals }}
        exitcode=${PIPESTATUS[0]}
        echo "::remove-matcher owner=luacheck-plain_error::"
        echo "::remove-matcher owner=luacheck-plain_warning::"
        if [ "$exitcode" -gt 1 ]; then
          exit $exitcode;
        else
          exit 0;
        fi
