name: Lua lint

on: 
  push:
    paths:
      - 'script/**'
      - '.luacheckrc'
      - '.vscode/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'script/**'
      - '.luacheckrc'
      - '.vscode/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  FILES_TO_CHECK: >-
    script
  VENDOR_PATH: .vscode/autocomplete
  LUACHECK_CONFIG: .luacheckrc
  CUSTOM_LUA_GLOBALS: >-
    ardm

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"
        
    - uses: leafo/gh-actions-luarocks@v4.1.0
      with:
        luarocksVersion: "3.7.0"
        
    - name: Install luacheck
      run: luarocks install luacheck

    - name: Reset autocomplete
      run: rm -rfv ${{ env.VENDOR_PATH }}

    - name: Checkout PJ-autocomplete
      uses: actions/checkout@v2
      with:
        repository: Warhammer-Mods/PJ-autocomplete
        path: ${{ env.VENDOR_PATH }}

    - name: Remove PJ-autocomplete meta files
      run: rm -rf ${{ env.VENDOR_PATH }}/{.git,.github}

    - name: Set Lua globals from vendor path
      id: lua-globals
      run: |
        chmod +x .vscode/update_lua_globals.sh
        .vscode/update_lua_globals.sh
        changes=$(git status --porcelain ${VENDOR_PATH} ${LUACHECK_CONFIG} | tr '\n' '\t')
        echo "::set-output name=changes::$changes"

    - name: Luacheck Lint
      id: luacheck
      shell: bash --noprofile --norc {0}
      run: |
        mkdir output
        echo "::add-matcher::.github/luacheck-plain.json"
        luacheck ${{ env.FILES_TO_CHECK }} \
          --formatter plain \
          --codes --ranges
        exitcode=${PIPESTATUS[0]}
        echo "::remove-matcher owner=luacheck-plain_error::"
        echo "::remove-matcher owner=luacheck-plain_warning::"
        if [ "$exitcode" -gt 1 ]; then
          exit $exitcode;
        else
          exit 0;
        fi

    - name: Commit files
      id: commit
      if: steps.lua-globals.outputs.changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ${VENDOR_PATH} ${LUACHECK_CONFIG}
        git commit -m "Update luacheck config"
        echo "::set-output name=finished::true"

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: steps.commit.outputs.finished && ! startsWith(github.ref, 'refs/tags/')
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
