name: Lua lint

on: 
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'
  workflow_dispatch:

  globals: >
    core
    cm
    out
    script_error
    is_table
    is_string
    is_number
    is_function
    is_boolean
    ardm

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"

    - name: Lint
      run: |
        luacheck script/{_lib,campaign} \
        --std lua51c \
        --globals ${{ env.globals }} \
        --formatter plain \
        --codes --ranges

        status=$?

        if [ "$status" -gt 1 ]; then
        exit $status
        else
        exit 0
        fi 
