name: Lua lint

on: 
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"

    - name: Lint
      run: >
        find script/ -type f -iname "*.lua"
        -exec luac {} \;
