name: Lua lint

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
    paths:
      - 'script/**'
      - '.luacheckrc'
      - '.vscode/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  workflow_dispatch:

jobs:
  db-check:
    uses: Warhammer-Mods/workflows/.github/workflows/lua-lint.yml@v2
    with:
      paths: script
      config_file: .luacheckrc
      vendor_path: .luarocks
      pr_enabled: true
      lua_version: 5.1
      custom_lua_globals: >-
        arkhan_expanded
    secrets:
      token: ${{ secrets.BOT_TOKEN }}
