name: Lua lint

on: 
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'
  workflow_dispatch:

env:
  globals: >-
    core
    cm
    out
    script_error
    is_table
    is_string
    is_number
    is_function
    is_boolean
    ardm

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - uses: nebularg/actions-luacheck@v1.1.0
      with:
        files: script/{_lib,campaign}
        args: --globals ${{ env.globals }}
        annotate: warnings
