name: Lua lint

on: 
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'
  workflow_dispatch:

env:
  WORKDIR: ./script
  FILES_TO_CHECK: >-
    _lib/
    campaign/
  VENDOR_PATH: .vscode
  CUSTOM_LUA_GLOBALS: >-
    ardm
  REGEX: ^[\s]*(?<filename>.+?):(?<lineStart>[0-9]+):([0-9]+|(?<columnStart>[0-9]+)-(?<columnEnd>[0-9]+)):\s*\(?(?<errorCode>([W|E])[0-9]+)?\)?\s*(?<errorDesc>.+?)$

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1"
        
    - uses: leafo/gh-actions-luarocks@v4.1.0
      with:
        luarocksVersion: "3.7.0"
        
    - name: Install luacheck
      run: luarocks install luacheck

    - name: Install show_globals.lua (courtesy of Egor Skriptunoff)
      working-directory: ${{ env.WORKDIR }}
      run: |
        wget -O show_globals.lua \
          https://gistcdn.githack.com/Egor-Skriptunoff/e4ab3bfc777faf4482a1b3f3ae19181b/raw/a39198cf62a52be7956abbff145a7fbf3f9a128a/show_globals.lua

    - name: Get Lua globals from vendor path
      id: lua-globals
      working-directory: ${{ env.WORKDIR }}
      run: |
        lua_files=$(find ${{ env.VENDOR_PATH }} -type f -iname "*.lua")
        globals=$(
          for f in $lua_files; do
            lua show_globals.lua W < $f | cut -f2
          done
          printf '%s' ${{ env.CUSTOM_LUA_GLOBALS }}
        )
        globals=$(tr ' ' '\n' <<<"${globals}" | sort -u | tr '\n' ' ')
        echo "::set-output name=globals::$globals"

    - name: Lint
      shell: bash --noprofile --norc {0}
      working-directory: ${{ env.WORKDIR }}
      run: |
        mkdir output
        luacheck ${{ env.FILES_TO_CHECK }} \
          --formatter plain \
          --codes --ranges \
          --globals ${{ steps.lua-globals.outputs.globals }} \
        | tee -a output/luacheck.txt
        exitcode=${PIPESTATUS[0]}
        if [ "$exitcode" -gt 1 ]; then
          exit $exitcode;
        else
          exit 0;
        fi

    - name: Highlight annotations (PR)
      uses: im-mortal/add-annotations-github-action@master
      with:
        check_name: Luacheck
        linter_output_path: ${{ env.WORKDIR }}/output/luacheck.txt
        commit_sha: ${{ github.event.pull_request.head.sha || github.sha }}
        mode: regex
        regex: ${{ env.REGEX }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: luacheck-results
        path: ${{ env.WORKDIR }}/output/luacheck.txt
        retention-days: 30