name: Build Packfile

on: 
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'support/**'
      - 'update/**'
  workflow_dispatch:
    inputs:
      paths:
        required: false
        type: string
        default: |
          * !.git/** !.vscode/** !**/.* !**/*.rockspec !matchers/*
        description: |
          A list of space-delimited glob patterns to include in the packfile.
      debug_enabled:
        description: Enable debug logging
        required: false
        type: boolean
        default: false

jobs:
  build-packfile-manual:
    uses: Warhammer-Mods/workflows/.github/workflows/packfile.yml@v2
    if: github.event_name == 'workflow_dispatch'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      paths: ${{ inputs.paths }}
      paths_separator: " "
      game: warhammer_2
      debug_enabled: ${{ inputs.debug_enabled }}
  build-packfile:
    uses: Warhammer-Mods/workflows/.github/workflows/packfile.yml@v2
    if: github.event_name != 'workflow_dispatch'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      paths: |
        *
        !.git/**
        !.vscode/**
        !**/.*
        !**/*.rockspec
      game: warhammer_2
